### ISSUE TITLE
Python version not correctly updating to 3.9

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/cdh-ansible#130] opened 2022-11-29 18:01 UTC
We're getting this error:

```
pulsys@cdh-test-prosody1:~$ sudo tail /var/log/apache2/ppa_error.log
[Tue Nov 29 18:00:55.640359 2022] [wsgi:error] [pid 4599:tid 140169124407040] [remote 128.112.203.144:36628] Traceback (most recent call last):
[Tue Nov 29 18:00:55.640404 2022] [wsgi:error] [pid 4599:tid 140169124407040] [remote 128.112.203.144:36628]   File "/var/www/ppa/ppa/wsgi.py", line 12, in <module>
[Tue Nov 29 18:00:55.640434 2022] [wsgi:error] [pid 4599:tid 140169124407040] [remote 128.112.203.144:36628]     from django.core.wsgi import get_wsgi_application
[Tue Nov 29 18:00:55.640466 2022] [wsgi:error] [pid 4599:tid 140169124407040] [remote 128.112.203.144:36628] ModuleNotFoundError: No module named 'django'
[Tue Nov 29 18:00:56.046126 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478] mod_wsgi (pid=4599): Target WSGI script '/var/www/ppa/ppa/wsgi.py' cannot be loaded as Python module.
[Tue Nov 29 18:00:56.046239 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478] mod_wsgi (pid=4599): Exception occurred processing WSGI script '/var/www/ppa/ppa/wsgi.py'.
[Tue Nov 29 18:00:56.046376 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478] Traceback (most recent call last):
[Tue Nov 29 18:00:56.046424 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478]   File "/var/www/ppa/ppa/wsgi.py", line 12, in <module>
[Tue Nov 29 18:00:56.046434 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478]     from django.core.wsgi import get_wsgi_application
[Tue Nov 29 18:00:56.046465 2022] [wsgi:error] [pid 4599:tid 140169132799744] [remote 128.112.203.145:38478] ModuleNotFoundError: No module named 'django'
```

It's possible that the python version is harder to switch when we're on apache vs nginx. we have to have the correct version of mod wsgi installed. @rlskoeser will investigate.

PR: https://github.com/Princeton-CDH/cdh-ansible/pull/129

**Comment by rlskoeser** [comment] 2022-11-29 21:28
duplicate of #128

**Closed by rlskoeser** 2022-11-29 21:28 UTC
Labels: chore
